### ISSUE TITLE
VirtualBox stuck/hung after booting

### ISSUE THREAD

**Issue by smpanaro** [AlexanderWillner/runMacOSinVirtualBox#1]
This looks great, thanks for putting it together!
I'm having a bit of trouble getting it working. I'm stuck between Steps 1 and 2 in your step-by-step guide. 
<img width="1451" alt="screen shot 2018-06-24 at 3 11 21 pm" src="https://user-images.githubusercontent.com/2950214/41822638-f5605c26-77c0-11e8-8ab5-0c6a4336cd0c.png">
I can't move the mouse in the VM to select a language.

I think this could be a problem with VirtualBox instead of your script, but figured I'd ask in case you'd seen anything similar.

Also, I'm curious what version of VirtualBox and macOS you're using. I'm using `VirtualBox v5.2.12 r122591 (Qt5.6.3)` and `macOS 10.13.5` and wonder if there might be a difference that matters there.

**Comment by AlexanderWillner** [comment]
If you can't use the mouse and can't use the keyboard, then there is an issue with the USB driver. I've added a check to the script: have you downloaded and installed the [Extension Pack](https://www.virtualbox.org/wiki/Downloads)?

**Comment by smpanaro** [comment]
That was it! I downloaded that (and tried the updated version of your script) and everything worked.

Thanks!
