### ISSUE TITLE
VM won't boot after pressing enter

### ISSUE THREAD

**Issue by Kerndog73** [AlexanderWillner/runMacOSinVirtualBox#102]
I'm getting stuck starting the VM after pressing enter.

![VirtualBox_Mojave_04_04_2020_15_36_06](https://user-images.githubusercontent.com/10371177/78419137-34b40980-768a-11ea-820c-0b3d4571893f.png)

I think I might be pressing enter at the wrong time. I'm really confused as to precisely when I'm supposed to press it. The installer was running, then the screen went black and white text appeared. That's when I pressed enter. Did I press it too early or too late? The video in the README rushes over this really quickly. Maybe I'm running into a completely separate problem?

Maybe there's no problem at all and this is meant to take a really long time?

---

When I don't press enter, I get stuck on the same screen. I thought it would go into an "installation loop" but it just stops right there. I should note that I applied #97. I'm not sure if the problem is related to that. Should I leave it running all night? Is it meant to take that long?

**Comment by Kerndog73** [comment]
I've tried a few times and keep getting stuck after pressing enter. I've known about this script for months but I've never been able to get it to work. 😞

**Comment by Kerndog73** [comment]
Used a [different script](https://github.com/myspaghetti/macos-guest-virtualbox) and it worked perfectly.

**Comment by AlexanderWillner** [comment]
Looks interesting. Thanks for the link. For what it's worth: used this script here 2 weeks ago and worked on a vanilla system, however, some edge cases might have been missed.
