### ISSUE TITLE
Trying to find a bootable device... Failed

### ISSUE THREAD

**Issue by wangghon** [AlexanderWillner/runMacOSinVirtualBox#106]
**To Reproduce**
Mac OS: Catalina 10.15.4
Visual box 6.1.6
1. run make all
2. input password
3. See error

**Additional context**
 - log file (see ```~/Library/Logs/runMojaveVirtualbox.log``` that is accessible via ```Console.app```).
 - screen shot
![image](https://user-images.githubusercontent.com/6700793/81474032-46b73800-9246-11ea-9e3c-0bb2eb06dd40.png)

**Comment by AlexanderWillner** [comment]
The log file might help

**Comment by wangghon** [comment]
@AlexanderWillner The issue was caused by  the installation in VM was interrupted by inputting enter in terminal.
Thanks.
