### ISSUE TITLE
Platform configuration...

### ISSUE THREAD

**Issue by dtpoirot** [AlexanderWillner/runMacOSinVirtualBox#108]
I wonder why there are 30 'ports' on the AHCI SATA Controller? I need about 4.

Why are there 35 'slots' in the Network Adapter section of the .VBOX file? I have only ever used 2.

**Comment by AlexanderWillner** [comment]
Most probably not related to this script. The screenshot shows how a new VM is configured.
<img width="763" alt="Screen Shot 2020-07-19 at 11 08 04" src="https://user-images.githubusercontent.com/307605/87871393-3511af80-c9b0-11ea-8a52-98c10e85c4df.png">

**Comment by AlexanderWillner** [comment]
Thanks for the feedback:
 - Ports: this was the default value. Now reduced specifically.
 - Slots: seems to be a default value as well, however, seems no easy/obvious way to remove/limit them
