### ISSUE TITLE
Support for macOS 10.16 (Big Sur)

### ISSUE THREAD

**Issue by AlexanderWillner** [AlexanderWillner/runMacOSinVirtualBox#110]
**To Reproduce**
1. Download macOS 10.16 (Big Sur)
2. Try to get install it in the VM

**Expected behavior**
Should work.

**Additional context**
- Error: "The operation couldn't be completed. (BIErrorDomain error 3.)"
- Seems to be an issue in other VMs as well (by judging initial Google results)
- See screen shot.

![Screen Shot 2020-06-23 at 12 46 33](https://user-images.githubusercontent.com/307605/85395113-ed823a00-b54f-11ea-9ed4-def5b88cb1d7.png)

**Comment by leogdion** [comment]
I was able to get past this point by setting the BoardID.
https://mrmacintosh.com/how-to-install-macos-big-sur-beta-on-vmware-fusion-parallels-desktop/

```
VBoxManage setextradata macOS-VM "VBoxInternal/Devices/efi/0/Config/DmiBoardProduct" "Mac-E1008331FDC96864"
```

I'll see how far it goes.

**Comment by leogdion** [comment]
The only issue I had was getting iCloud setup. I'm wondering if setting up a model number in VirtualBox would fix this.
![LWScreenShot 2020-06-23 at 3 30 51 PM](https://user-images.githubusercontent.com/1036388/85489120-8a1ef900-b59d-11ea-9c7f-2987d22423a6.png)

Otherwise the VM seems to be working.
<img width="908" alt="Screen Shot 2020-06-23 at 6 36 28 PM" src="https://user-images.githubusercontent.com/1036388/85489158-96a35180-b59d-11ea-8b3b-9bb6ac512491.png">

**Comment by AlexanderWillner** [comment]
> The only issue I had was getting iCloud setup. I'm wondering if setting up a model number in VirtualBox would fix this.

For (later) reference for a potential fix:
 - https://www.wikigain.com/fix-macos-mojave-imessage-icloud-app-store-vmware/
 - https://github.com/myspaghetti/macos-virtualbox/issues/135
 - https://stackoverflow.com/questions/40040679/app-store-not-connecting-on-mac-through-vmware-virtual-machine

**Comment by leogdion** [comment]
Serial number didn't work. I'm going to try model number when I get a chance to restart.

**Comment by AlexanderWillner** [comment]
> Serial number didn't work. I'm going to try model number when I get a chance to restart.

Interesting. "Works for me" ;) Which OS are you using?

**Comment by leogdion** [comment]
Host:
<img width="189" alt="Screen Shot 2020-06-24 at 11 13 38 AM" src="https://user-images.githubusercontent.com/1036388/85582938-d6a11d80-b60b-11ea-80f8-1f42d25b9567.png">
Guest:
<img width="180" alt="Screen Shot 2020-06-24 at 11 13 28 AM" src="https://user-images.githubusercontent.com/1036388/85582950-d86ae100-b60b-11ea-999b-5576b492a126.png">

VirtualBox:
<img width="752" alt="Screen Shot 2020-06-24 at 11 13 47 AM" src="https://user-images.githubusercontent.com/1036388/85582929-d4d75a00-b60b-11ea-96ba-b42ac02a845c.png">

**Comment by AlexanderWillner** [comment]
ok, seems that the command `ioreg -c IOPlatformExpertDevice -d 2 | awk -F\" '/IOPlatformSerialNumber/{print $(NF-1)}'` works on macOS Mojave but not on Catalina then...

**Comment by AlexanderWillner** [comment]
@leogdion does the fix at #111 help with your issue?

**Comment by leogdion** [comment]
No, I'm stilling having issues signing into iCloud. Everything else seems to work fine.
<img width="1412" alt="Screen Shot 2020-06-29 at 8 20 41 AM" src="https://user-images.githubusercontent.com/1036388/86004568-821de980-b9e1-11ea-9a73-5d3ee7bec859.png">

**Comment by startergo** [comment]
> ioreg -c IOPlatformExpertDevice -d 2 | awk -F\" '/IOPlatformSerialNumber/{print $(NF-1)}'

It works on Catalina. I got iMessage and iCloud working. You need all these values:
https://github.com/myspaghetti/macos-virtualbox/blob/master/macos-guest-virtualbox.sh#L33

**Comment by startergo** [comment]
You can add these in the script:
```
readonly VM_SYSTEM_FAMILY="$(system_profiler SPHardwareDataType |  awk -F: ' /Model Name/ { print $2 } ')"
readonly VM_SYSTEM_PRODUCT="$(system_profiler SPHardwareDataType |  awk -F: ' /Model Identifier/ { print $2 } ')"
readonly VM_SYSTEM_UUID="$(system_profiler SPHardwareDataType |  awk -F: ' /Hardware UUID/ { print $2 } ')"
readonly VM_SYSTEM_REVS="$(system_profiler SPHardwareDataType |  awk -F: ' /Apple ROM Info/ { print $2 } ')"
readonly VM_SYSTEM_BIOS="$(system_profiler SPHardwareDataType |  awk -F: ' /Boot ROM Version/ { print $2 } ')"
readonly VM_SYSTEM_SN="$(system_profiler SPHardwareDataType |  awk -F: ' /Serial Number (system)/ { print $2 } ')"
readonly VM_ROM="$(nvram 4D1EDE05-38C7-4A6A-9CC6-4BCCA8B38C14:ROM')"
readonly VM_MLB="$(nvram 4D1EDE05-38C7-4A6A-9CC6-4BCCA8B38C14:MLB')"

```
You are missing the ROM and MLB values in the script so you will have to adjust them:
```
VBoxManage setextradata "macOS" "VBoxInternal/Devices/efi/0/Config/DmiBoardSerial" "VM_MLB"

```
I am not sure how the VM_ROM can be injected.

**Comment by AlexanderWillner** [comment]
Nice. Thank you! I'll check.

**Comment by AlexanderWillner** [comment]
Seems that Apple ROM Info is empty here. Script:
```bash
echo "Collecting system information..."
readonly VM_SYSTEM_FAMILY="$(system_profiler SPHardwareDataType |  awk -F': ' ' /Model Name/ { print $2 } ')"
readonly VM_SYSTEM_PRODUCT="$(system_profiler SPHardwareDataType |  awk -F': ' ' /Model Identifier/ { print $2 } ')"
readonly VM_SYSTEM_UUID="$(system_profiler SPHardwareDataType |  awk -F': ' ' /Hardware UUID/ { print $2 } ')"
readonly VM_SYSTEM_REVS="$(system_profiler SPHardwareDataType |  awk -F': ' ' /Apple ROM Info/ { print $2 } ')"
readonly VM_SYSTEM_BIOS="$(system_profiler SPHardwareDataType |  awk -F': ' ' /Boot ROM Version/ { print $2 } ')"
readonly VM_SYSTEM_SN="$(system_profiler SPHardwareDataType |  awk -F': ' ' /Serial Number \(system\)/ { print $2 } ')"
readonly VM_ROM="$(nvram '4D1EDE05-38C7-4A6A-9CC6-4BCCA8B38C14:ROM' |  awk -F' ' ' { print $2 } ')"
readonly VM_MLB="$(nvram '4D1EDE05-38C7-4A6A-9CC6-4BCCA8B38C14:MLB' |  awk -F' ' ' { print $2 } ')"

echo "Collected system information..."
echo "VM_SYSTEM_FAMILY: $VM_SYSTEM_FAMILY"
echo "VM_SYSTEM_PRODUCT: $VM_SYSTEM_PRODUCT"
echo "VM_SYSTEM_UUID: $VM_SYSTEM_UUID"
echo "VM_SYSTEM_REVS: $VM_SYSTEM_REVS" # no output here on my system
echo "VM_SYSTEM_BIOS: $VM_SYSTEM_BIOS"
echo "VM_SYSTEM_SN: $VM_SYSTEM_SN"
echo "VM_ROM: $VM_ROM"
echo "VM_MLB: $VM_MLB"
```

**Comment by startergo** [comment]
> Seems that Apple ROM Info is empty here. Script:
> 
> ```shell
> echo "Collecting system information..."
> readonly VM_SYSTEM_FAMILY="$(system_profiler SPHardwareDataType |  awk -F': ' ' /Model Name/ { print $2 } ')"
> readonly VM_SYSTEM_PRODUCT="$(system_profiler SPHardwareDataType |  awk -F': ' ' /Model Identifier/ { print $2 } ')"
> readonly VM_SYSTEM_UUID="$(system_profiler SPHardwareDataType |  awk -F': ' ' /Hardware UUID/ { print $2 } ')"
> readonly VM_SYSTEM_REVS="$(system_profiler SPHardwareDataType |  awk -F': ' ' /Apple ROM Info/ { print $2 } ')"
> readonly VM_SYSTEM_BIOS="$(system_profiler SPHardwareDataType |  awk -F': ' ' /Boot ROM Version/ { print $2 } ')"
> readonly VM_SYSTEM_SN="$(system_profiler SPHardwareDataType |  awk -F': ' ' /Serial Number \(system\)/ { print $2 } ')"
> readonly VM_ROM="$(nvram '4D1EDE05-38C7-4A6A-9CC6-4BCCA8B38C14:ROM' |  awk -F' ' ' { print $2 } ')"
> readonly VM_MLB="$(nvram '4D1EDE05-38C7-4A6A-9CC6-4BCCA8B38C14:MLB' |  awk -F' ' ' { print $2 } ')"
> 
> echo "Collected system information..."
> echo "VM_SYSTEM_FAMILY: $VM_SYSTEM_FAMILY"
> echo "VM_SYSTEM_PRODUCT: $VM_SYSTEM_PRODUCT"
> echo "VM_SYSTEM_UUID: $VM_SYSTEM_UUID"
> echo "VM_SYSTEM_REVS: $VM_SYSTEM_REVS" # no output here on my system
> echo "VM_SYSTEM_BIOS: $VM_SYSTEM_BIOS"
> echo "VM_SYSTEM_SN: $VM_SYSTEM_SN"
> echo "VM_ROM: $VM_ROM"
> echo "VM_MLB: $VM_MLB"
> ```
I have corrected the parameters. Please re-check my previous post. There were some empty strings upfront which I removed as well.  You have some ' ' single quotes which are not supposed to be there. Also check this zsh script (replace zsh in the beginning with bash if you use bash)

```
#!/usr/bin/env zsh

readonly HOST_SERIAL="$(ioreg -c IOPlatformExpertDevice -d 2 | awk -F\" '/IOPlatformSerialNumber/{print $(NF-1)}')"
readonly HOST_ID="$(ioreg -l | grep "board-id" | awk -F\" '/board-id/{print $(NF-1)}')"
readonly HOST_UUID="$(ioreg -l -p IODeviceTree | awk -F"\<|>" '/"system-id"/{print $(NF-1)}')"
readonly VM_SYSTEM_FAMILY="$(system_profiler SPHardwareDataType |  awk -F" " ' /Model Name/ { print $2 } ')"
readonly VM_SYSTEM_PRODUCT="$(system_profiler SPHardwareDataType |  awk -F" " ' /Model Identifier/ { print $2 } ')"
readonly VM_SYSTEM_UUID="$(system_profiler SPHardwareDataType |  awk -F" " ' /Hardware UUID/ { print $2 } ')"
readonly VM_SYSTEM_REVS="$(system_profiler SPHardwareDataType |  awk -F" " ' /Apple ROM Info/ { print $2 } ')"
readonly VM_SYSTEM_BIOS="$(system_profiler SPHardwareDataType |  awk -F" " ' /Boot ROM Version/ { print $2 } ')"
readonly VM_SYSTEM_SN="$(system_profiler SPHardwareDataType |  awk -F" " ' /Serial Number/ { print $2 } ')"
readonly ROM="$(nvram 4D1EDE05-38C7-4A6A-9CC6-4BCCA8B38C14:ROM |  awk -F" " ' /ROM/ { print $2 } ')"
readonly MLB="$(nvram 4D1EDE05-38C7-4A6A-9CC6-4BCCA8B38C14:MLB |  awk -F" " ' /MLB/ { print $2 } ')"

Echo DmiSystemSerial="'$HOST_SERIAL'" > macos_vm_vars_file
Echo DmiBoardProduct="'$HOST_ID'" >> macos_vm_vars_file
Echo SYSTEM_UUID="'$HOST_UUID'" >> macos_vm_vars_file
Echo DmiSystemFamily="'$VM_SYSTEM_FAMILY'" >> macos_vm_vars_file
Echo DmiSystemProduct="'$VM_SYSTEM_PRODUCT'" >> macos_vm_vars_file
Echo DmiSystemUuid="'$VM_SYSTEM_UUID'" >> macos_vm_vars_file
Echo DmiOEMVBoxRev="'$VM_SYSTEM_REVS'" >> macos_vm_vars_file
Echo DmiBIOSVersion="'$VM_SYSTEM_BIOS'" >> macos_vm_vars_file
Echo DmiBoardSerial="'$VM_SYSTEM_SN'" >> macos_vm_vars_file
echo MLB="'$MLB'" >> macos_vm_vars_file
Echo ROM="'$ROM'" >> macos_vm_vars_file
echo SYSTEM_INTEGRITY_PROTECTION="'77'" >> macos_vm_vars_file

```
