### ISSUE TITLE
Big Sur VDI not created

### ISSUE THREAD

**Issue by psco** [AlexanderWillner/runMacOSinVirtualBox#112]
**To Reproduce**
On latest Mojave on an external drive drive of a MacBook Pro: I have "Install macOS Big Sur Beta" in the Applications folder and execute in a bash shell
```
export VM_NAME=BigSurBeta
export VM_SIZE=65536
make all
```

After some time the VM starts but there is no disk where Big Sur could be installed onto

**Expected behavior**
There is a disk available for the installer

**Additional context**
- [runMacOSVirtualbox.log](https://github.com/AlexanderWillner/runMacOSinVirtualBox/files/4941891/runMacOSVirtualbox.log)
- I'm running this on an external drive
- After the failed installation the main drive of the MacBook Pro is not available for restart (was is ejected by accident?)

**Comment by AlexanderWillner** [comment]
Fixed this in my last commit a few hours ago. Can you test again?

**Comment by psco** [comment]
I think I found the problem: This time I removed an external disk with 4 partitions before embarking on the "make all" and the VDI disk was created. Maybe there is an issue when one has a lot of disks attached.

**Comment by AlexanderWillner** [comment]
Good to hear that it’s working for you
