### ISSUE TITLE
Feature request: Run macOS 10.16 Big Sur (and other versions) in VirtualBox on Linux, say, Ubuntu.

### ISSUE THREAD

**Issue by hongyi-zhao** [AlexanderWillner/runMacOSinVirtualBox#114]
Hi,

I want to use this script for running macOS 10.16 Big Sur (and other versions) in VirtualBox on Linux, say, Ubuntu. Is it possible?

Regards
HY

**Comment by AlexanderWillner** [comment]
There are other scripts on GitHub to get macOS up and running on other operating systems. Maybe, just as an example, https://github.com/kholia/OSX-KVM might help.
