### ISSUE TITLE
Weird bug, IDK where to log

### ISSUE THREAD

**Issue by minhtt159** [AlexanderWillner/runMacOSinVirtualBox#117]
I have my installer in /Application folder, then run `make all`
After a while, VirtualBox shows this bug. 

![image](https://user-images.githubusercontent.com/4847344/94374906-ced8a400-0139-11eb-8d44-ddc0c9829845.png)

**Comment by minhtt159** [comment]
The installer is macOS 10.15.4

**Comment by humanpoweredd** [comment]
If booting fails, you'll need to try applying a different CPU profile and CPUID setting.

I get a similar problem on my AMD machine if I don't modify the VM settings. 

From command line/Terminal:

VBoxManage modifyvm "<VM name>" --cpu-profile "Intel Core XXXXXX"  --cpuidset <xxxxxxxxx-xxxxxxxxxx-xxxxxxxxxx>

[See this](https://drive.google.com/file/d/1RmbvgT_W0gpbrhwjiIlfMh7NJnnbgscP/view).

Hopefully that'll work.
