### ISSUE TITLE
Mojave 10.14.6 VM on BigSur host - Initial run hangs on "Start RandomSeed"

### ISSUE THREAD

**Issue by edudnyk** [AlexanderWillner/runMacOSinVirtualBox#130]
**To Reproduce**

1. Install Virtual Box 6.1.22 r144080
2. Run `make download`, download Mojave 10.14.6.
2. Copy Installer app to /Applications
3. Run `make all`
4. Observe Virtual Box VM screen 

**Expected behavior**
Installer starts

**Additional context**
 - log file that is accessible via ```Console.app``` - see [runMacOSVirtualbox.log](https://github.com/AlexanderWillner/runMacOSinVirtualBox/files/6530546/runMacOSVirtualbox.log)
 - screen shot <img width="840" alt="Screenshot 2021-05-24 at 09 25 54" src="https://user-images.githubusercontent.com/52015789/119311979-0d474400-bc72-11eb-945d-59f6ab7c6a6f.png">

**Comment by JJ-8** [comment]
I found a solution:
[Disable "Enable Nested Paging"](https://www.reddit.com/r/hackintosh/comments/aij0v0/stuck_at_start_randomseed_on_mojave_in_virtualbox/). You may first want to [import the VM in the virtualbox GUI](https://superuser.com/a/855565).

**Comment by AlexanderWillner** [comment]
Thanks! Hope the change fixed the issue.
