### ISSUE TITLE
Enabling FileVault prevents system boot

### ISSUE THREAD

**Issue by dsuriano** [AlexanderWillner/runMacOSinVirtualBox#14]
First: Thank you very much for making your scripts available. They've been a huge asset in getting a macOS VM up and running.

I'm fairly sure this has nothing to do with your scripts, but I was hoping that you may have some insight that helps me or others get past this current blocker.

After I've successfully created / set up a new macOS VM (High Sierra 10.13.6), I need to enable FileVault in order to install some company VPN software that requires it's enabled.

The problem is that after FileVault successfully encrypts the drive, I'm no longer able to boot into it.  My Clover GUI options no longer lists `Boot macOS from Mojave`, but is now replaced with `Boot FileVault Prebooter from Preboot`.  If I select this new option, I'm presented with the standard initial user login screen asking for my account password, but I'm unable to enter it as the keyboard and mouse seem to be disabled. 

If I boot into recovery mode, I'm able to see my encrypted drive as a selectable option within `Choose startup disk` after entering the password to decrypt it... but when it reboots I'm back to the same boot issue with the `Boot FileVault Prebooter from Preboot` and the lack of keyboard/mouse input. 

Happy to provide more specific details if you think it might help in successfully being able to use FireVault within the VM.

**Comment by AlexanderWillner** [comment]
Mh, interesting. Unfortunately, I've currently no idea why mouse and keyboard are not working in this specific case :/

**Comment by dsuriano** [comment]
Thanks for taking time to respond... out of curiosity, have you ever successfully attempted to turn on FileVault within a macOS VM? It'd be interesting to see if this is something specific to my config or a larger issue with VirtualBox booting FileVault encrypted drives.

**Comment by dsuriano** [comment]
Cool. Thanks for the direction and taking time to respond. All the resources I've seen so far are geared towards the Hackentosh crowd using non-Apple boxes ... still haven't seen anyone trying to fix this for the Apple VM crowd. 

No solution just yet, but closing since it's completely unrelated to the awesome work you've done in this repo.
