### ISSUE TITLE
Won't get the Clover boot menu

### ISSUE THREAD

**Issue by fredericblaison** [AlexanderWillner/runMacOSinVirtualBox#16]
**To Reproduce**
1. Follow onscreen instruction with success until step 6
2. After restarted up the WM, I'm getting the UEFI interactive shell interface
3. Mapping table displays FS1 and FS0 but I'm not able to find how to switch into Clover boot menu

**Expected behavior**
Start macOS in the Clover boot menu

**Additional context**
Tried fs1: and fs0: where I enter \EFI\Boot\Bootx64.efi
No luck.

**Comment by fredericblaison** [comment]
Thanks much **Alexander** but in which directory I should run `make` ?

**Comment by fredericblaison** [comment]
```tar: Error opening archive: Failed to open 'clover.tar'
created: /tmp/macOS-MojaveClover.dmg
cp: /Volumes/Clover-v2.4k-4533-X64/*: No such file or directory
cp: directory /Volumes/NO NAME/EFI/CLOVER does not exist
cp: directory /Volumes/NO NAME/EFI/CLOVER/drivers64UEFI does not exist```
Let me see it.

**Comment by fredericblaison** [comment]
I believe that I have an issue with `xz` which is installed but not linked in `/usr/local` due to macOS `SIP`

```
/Applications/RunMojaveVirtualbox.app/Contents/Resources/runMojaveVirtualbox.sh: line 213: xz: command not found
tar: Error opening archive: Failed to open 'clover.tar'
```

**Comment by fredericblaison** [comment]
I'm trying running `brew link xz` then I rebuild from scratch (step 1) after erased everything.

**Comment by fredericblaison** [comment]
**Fixed**

**Issue**
On `macOS SIERRA` or sup, `xy` can be installed but not properly linked making `Clover.tar` to fail on decompression.

**Workaround**
Prerequis
- `Brew`

Step
1. Install `xy` with Brew if not installed by the script
2. Run `$ brew link xz`
3. Delete previous Mojave VM from VirtualBox (Delete All Files)
4. Empty `tmp` or reboot computer
5. Re start from step 1

**Comment by AlexanderWillner** [comment]
```/usr/local``` is not protected by ```SIP```. I added another additional ```brew link xz``` to the setup script. Hope this would fix the issue for others. Thanks.

**Comment by fredericblaison** [comment]
Until I'm wrong, since `SIERRA`, `/usr/local` permissions can't no longer be modified with `chown`. I believe it is due on new `SIP` polcies (?). It makes necessary to create a subfolder in `/usr/local` prior to be able to install and set any file with appropriate permissions or links; one of the reason why `Brew` can get some issues.

**Comment by mrahmadt** [comment]
Just tried this today and I’m getting the same issue 

Ps: xz already linked

**Comment by AlexanderWillner** [comment]
Can you provide the output of the log file?

**Comment by AlexanderWillner** [comment]
I removed clover from the setup. So might be fixed now.
