### ISSUE TITLE
Hang when running against public Mojave release

### ISSUE THREAD

**Issue by bland328** [AlexanderWillner/runMacOSinVirtualBox#19]
I don't know if the problem is with the released Mojave installer, or with my system. Perhaps in the GM of Mojave, the `createinstallmedia` behavior has changed? I'm running this under High Sierra.

When I put in my administrative password at this line of the script:

`sudo "$INST_BIN" --nointeraction --volume "$DST_VOL"`

it simply never returns. Or, at least, doesn't for an hour.

I've tried simplifying it to:

`sudo "$INST_BIN" --volume "$DST_VOL"`

in case `createinstallmedia` has anything to tell me, but nothing changed.

Is anyone else up against this?

**Comment by AlexanderWillner** [comment]
Anything of interest in ```$HOME/Library/Logs/runMojaveVirtualbox.log```?

**Comment by bland328** [comment]
Nothing interesting, sadly. Just this, with the exit status 130 being when I hit Ctrl-C:

`[2018-10-01 22:05:49] Running checks (around 1 second)...`
`[2018-10-01 22:05:49] .`
`[2018-10-01 22:05:49] Opening GUI...`
`[2018-10-01 22:05:50] Creating image '/tmp/macOS-Mojave.dmg' (around 20 seconds, version 14.0.22, will need sudo)...`
`[2018-10-01 22:05:50] .`
`[2018-10-01 22:22:13] line 168 - command 'sudo "$INST_BIN" --volume "$DST_VOL"' exited with status: 130.`
`[2018-10-01 22:22:13] In ::createImage::main::main called at line 307.`
`[2018-10-01 22:22:13] From function ::createImage::main::main (line 307).`
`[2018-10-01 22:22:13] Look at /Users/brian/Library/Logs/runMojaveVirtualbox.log for details (or use Console.app). Press enter in the terminal when done...`

**Comment by AlexanderWillner** [comment]
My guess is that it's waiting for your password. It might look like this when running the CLI version:
```
$ bash runMojaveVirtualbox.sh installer
Creating image '/Users/awi/VirtualBox VMs//macOS-Mojave.dmg' (around 20 seconds, version 14.0.22, will need sudo)....
Password:
```

**Comment by bland328** [comment]
Ah...I should've said that it does ask for my password. Strange!

**Comment by AlexanderWillner** [comment]
What the script is doing:
```
$ hdiutil attach ~/VirtualBox\ VMs/macOS-Mojave.dmg -mountpoint /Volumes/macOS-Mojave
$ sudo "/Applications/Install macOS Mojave.app/Contents/Resources/createinstallmedia" --nointeraction --volume "/Volumes/macOS-Mojave" --applicationpath "/Applications/Install macOS Mojave.app"
```

**Comment by bland328** [comment]
In my case, when

`sudo "$INST_BIN" --nointeraction --volume "$DST_VOL"`

executes, I'm prompted for my password, and hours later it still has not returned.

I've even added additional output as the very next line of the script, but it is never executed.
