### ISSUE TITLE
Installing Mojave in VBox hangs

### ISSUE THREAD

**Issue by christau** [AlexanderWillner/runMacOSinVirtualBox#20]
First of all, many thanks for your tool.
I checked out the latest version and ran 'make all'. Everything succeeded.
Then I formatted the disk with the disk util, according to the step by step guide.
But when I try to start the system installation, nothing happens. 
![bildschirmfoto 2018-10-02 um 11 35 00](https://user-images.githubusercontent.com/472189/46341379-35548580-c638-11e8-8113-360992e694d9.png)
I almost waited an hour. 
I'm runnig VBox 5.2.18 on macOS 10.12.6
Has anyone experienced the same behaviour? Any hints on getting over this?

**Comment by AlexanderWillner** [comment]
Mh, I’ve not seen this before. Not sure what happens here. Running ´
make clean stashˋ (deletes everything) would be my first attempt.

**Comment by christau** [comment]
Thanks for your reply.
I repeated the same procedure a second time:
```
make clean stash
make all
```
But with the same ending, that the installation of macOS itself wont start.
The installation bundle was downloaded from the appstore on the day of the issue creation.

**Comment by christau** [comment]
I installed it under 10.14 and it finally worked. Thanks for your help.

**Comment by dynek** [comment]
I'm having the same issue described by @christau.
Host is Catalina 10.15.1 and I'm trying to install Mojave.
It just freezes there:
![2020-01-03 at 22 16](https://user-images.githubusercontent.com/591091/71749847-e4ed5880-2e76-11ea-816e-083d45efeb7d.png)

If I open a terminal for instance, then go back to the same menu and click `Install MacOS` again I get "This copy of the Install macOS Mojave application is damaged, and can't be used to install macOS.".

**Comment by dynek** [comment]
Well that's crazy - I redownloaded Mojave and it worked. How odd.
