### ISSUE TITLE
createImage() step fails

### ISSUE THREAD

**Issue by bentech** [AlexanderWillner/runMacOSinVirtualBox#24]
**To Reproduce**
Steps to reproduce the behaviour:
run script or .app

**Additional context**
```
[2018-10-08 11:03:06] Creating iso '/Users/bentech/VirtualBox VMs//macOS-Mojave.iso.cdr' (around 25 seconds)...
[2018-10-08 11:03:06] .
hdiutil: convert failed - Resource temporarily unavailable
"disk2" ejected.

```
I manually created the image with 
`hdiutil convert ~/VirtualBox\ VMs/macOS-Mojave.dmg -format UDTO -o ~/VirtualBox\ VMs/macOS-Mojave.iso.cdr` and ran the script again. It then worked.

**Comment by AlexanderWillner** [comment]
Mh, ```Resource temporarily unavailable``` could indicate that there are terminal windows, applications, ... that were using the image. Should make the script more robust when there is another report.

**Comment by AlexanderWillner** [comment]
to be reopened if this happens again somewhere
