### ISSUE TITLE
Run RunMojaveVirtualbox.app error

### ISSUE THREAD

**Issue by Wizz86** [AlexanderWillner/runMacOSinVirtualBox#26]
**To Reproduce**
1. run RunMojaveVirtualbox.app
2. Progress dialog stops with error :
DEBUG: line 128 - command 'exit 3' exited with status: 3.
DEBUG: In ::runChecks::main::main called at line 308.
DEBUG: From function ::runChecks::main::main (line 308).

**Expected behavior**
Install a Mojave VM

**Additional context**
iMac 13,2 - macOS 10.13.3 - SSD 500G APFS - RAM 16GB
 - log file  attached
[Progress dialog.pdf](https://github.com/AlexanderWillner/runMacOSinVirtualBox/files/2466082/Progress.dialog.pdf)
[runMojaveVirtualbox-log.pdf](https://github.com/AlexanderWillner/runMacOSinVirtualBox/files/2466084/runMojaveVirtualbox-log.pdf)

**Comment by Wizz86** [comment]
solved after installing Homebrew

**Comment by AlexanderWillner** [comment]
Thanks. Added this to the FAQ.
