### ISSUE TITLE
How do you download OS in first step?

### ISSUE THREAD

**Issue by xahon** [AlexanderWillner/runMacOSinVirtualBox#27]
**To Reproduce**
1. Go to 'https://itunes.apple.com/us/app/macos-mojave/id1398502828?mt=12'
2. See no download button even if logged in
![image](https://user-images.githubusercontent.com/18731681/46773333-22306c80-cd40-11e8-98e6-16e69176123c.png)

**Expected behavior**
I expected to see a button that I click and `.iso` download

**Comment by Wizz86** [comment]
The Install packages for macOS are not .ISO  ut application ex. : Install macOS Mojave.app.
Download this and folow the indicated process to install giving that downloaded file as the source to install.

**Comment by xahon** [comment]
@Wizz86 what?

**Comment by AlexanderWillner** [comment]
You need to use a Mac to download Mojave. However, there are workarounds. Google for "download macos without Mac"
