### ISSUE TITLE
sqllite3 kext history

### ISSUE THREAD

**Issue by agjs** [AlexanderWillner/runMacOSinVirtualBox#29]
Hey Alexander and thanks for creating this image. Everything works other then finding any records in kext_load_history (or any other table). I'm trying to debug a kext extension (Soundflower) but when I query for any records, it's always empty.

Is there a reason for this behaviour considering we are in virtual environment? Is there any way for this image to properly store those in sqlite3?

**Comment by AlexanderWillner** [comment]
Mh, the only limitations I'm aware of are graphics related. However, I've not used/tested sound so far. Might happen that you need to look a bit into the Hackintosh community and google for macOS, VirtualBox, Audio, Multibeast, ...

**Comment by AlexanderWillner** [comment]
Best starting point might be https://forums.virtualbox.org/search.php?keywords=audio&fid%5B0%5D=22 and maybe even http://incomingtech.weebly.com/how-to-enable-sound-on-mac-os-x-in-virualbox.html
