### ISSUE TITLE
Feature-Request: Allow other storage sizes

### ISSUE THREAD

**Issue by max-wittig** [AlexanderWillner/runMacOSinVirtualBox#30]
The only way to get a larger disk, is to modify the read-only property `readonly VM_SIZE="32768"`

Maybe this should be configurable with environment variables?

**Comment by AlexanderWillner** [comment]
Thanks. Done. Tested with ```VM_NAME=Foo VM_SIZE=128000 VM_RAM=2048 VM_VRAM=64 VM_CPU=1 bash runMojaveVirtualbox.sh all```

**Comment by max-wittig** [comment]
@AlexanderWillner That was quick! Thank you! :+1:
