### ISSUE TITLE
Screen Resolution

### ISSUE THREAD

**Issue by mrahmadt** [AlexanderWillner/runMacOSinVirtualBox#33]
Finally, I managed to run Mojave in Virtualbox :)

Thanks for the excellent work.

Just one small issue, how can I change the resolution of the guest? currently, I can not see any option other than 1680x1050 (even if I press "option"), the current resolution is very big for my screen.

**Comment by nampdn** [comment]
You can try this:
```bash
VBoxManage setextradata "MacOS" "CustomVideoMode1" "1680x1050x32"
```

**Comment by AlexanderWillner** [comment]
The screen resolution in https://github.com/AlexanderWillner/runMacOSinVirtualBox/blob/master/config.plist also has to be updated accordingly.

**Comment by IanSavchenko** [comment]
@AlexanderWillner Do we also need to recreate the machine?

**Comment by n1kk** [comment]
I'v changed resolution in the plist and via terminal command to "1440x900" and rebuild clover image but this is what I got in the end:
![screen shot 2018-11-07 at 4 21 02 pm](https://user-images.githubusercontent.com/5442968/48137742-62d1c600-e2ab-11e8-8117-55ad35fcd890.png)

**Comment by AlexanderWillner** [comment]
You also have to modify the screen resolution of the VM:
{{{
    VBoxManage setextradata "macOS-Mojave" "CustomVideoMode1" "1440x900x32"
    VBoxManage setextradata "macOS-Mojave" VBoxInternal2/EfiGraphicsResolution "1440x900"
}}}

**Comment by AlexanderWillner** [comment]
What about setting the screen resolution via boot flag using e.g. ```-v "Graphics Mode"="1280x800x32@60Hz"```

**Comment by AlexanderWillner** [comment]
I removed clover from the setup. So might be fixed now.
