### ISSUE TITLE
Mouse integration (MI) is on, after export, mouse is captured and stuck

### ISSUE THREAD

**Issue by HoudayerPierre** [AlexanderWillner/runMacOSinVirtualBox#39]
If someone have an idea to use mouse integration (on) after export/import.
Everything works with my base VM, package it with vagrant, no working mouse after import.
I tried with additional USB mouse in connected devices mount in the VM.

I'm out of ideas :(.

**To Reproduce**

1. Have working 10.14.**1** Mojave VM with mouse integration (MI) is on and working on host-guest (no capture)
2. Package with vagrant to get a clean base box to share (vagrant package)
3. Import with vagrant and start (vagrant up)
4. Boot ok, the mouse is captured but stuck (No mouse integration on)

**Expected behavior**
Working mouse on capture, but it will be better with mouse integration on

**Comment by HoudayerPierre** [comment]
Ok, I think I found something it can work.
Change configs to use "USB2" and the profile "Mac OS X (64 bits)" boot (mouse is now in integration on but not working) stop VM
Switch back to "USB3" and the profile "macOS 10.13 High Sierra (64 bits)" and boot and this can make the mouse integration on and working.

**Comment by oliverchapple** [comment]
mouse not working it will not let me pick 2.0 or 3.0 so it on 1.0 but won,t work so i can't install the system can you help me

**Comment by AlexanderWillner** [comment]
You have to install the [VirtualBox Extension Pack](https://www.virtualbox.org/wiki/Downloads) to enable USB 3.0. MacOS only supports USB 3.0 out of the box.

**Comment by oliverchapple** [comment]
How do you do Apple mouse

Sent from my iPad

On 26 Apr 2019, at 06:31, Alex <notifications@github.com<mailto:notifications@github.com>> wrote:


You have to install the VirtualBox Extension Pack<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.virtualbox.org%2Fwiki%2FDownloads&data=02%7C01%7C%7Cb33af1d1a06b4c3e7c2508d6ca08621e%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636918534679008994&sdata=BW4r5JMVKeDZNhEudcnzS%2Bss%2FZCXS%2BIc4zSNG1U1PWI%3D&reserved=0> to enable USB 3.0. MacOS only supports USB 3.0 out of the box.

**Comment by AlexanderWillner** [comment]
I’m installing the extension pick and select USB 3.0. Then the mouse support is working.

**Comment by oliverchapple** [comment]
Did you get Apple maps working

Sent from my iPad

On 26 Apr 2019, at 11:48, Alex <notifications@github.com<mailto:notifications@github.com>> wrote:


I’m installing the extension pick and select USB 3.0. Then the mouse support is working.

**Comment by AlexanderWillner** [comment]
See FAQ: There is currently no 3D acceleration, therefore some applications do not work. For example Apple Maps.

**Comment by oliverchapple** [comment]
Will they add it

Sent from my iPad

On 26 Apr 2019, at 18:54, Alex <notifications@github.com<mailto:notifications@github.com>> wrote:


See FAQ: There is currently no 3D acceleration, therefore some applications do not work. For example Apple Maps.

**Comment by AlexanderWillner** [comment]
Well, nobody outside of Oracle knows for sure, but I doubt it.

**Comment by oliverchapple** [comment]
after that update Mac Mojave’s Siri closing by it self

Sent from my iPad

On 27 Apr 2019, at 14:40, Alex <notifications@github.com<mailto:notifications@github.com>> wrote:


Well, nobody outside of Oracle knows for sure, but I doubt it.
