### ISSUE TITLE
running clover boot

### ISSUE THREAD

**Issue by judoal** [AlexanderWillner/runMacOSinVirtualBox#40]
**To Reproduce**
1. At Step 5, how to remove the .iso.cdr and leave an empty disk?  I simply removed it
2.  At step 6, it is no clear how to start the clover boot manager.  I pressed  enter while the host cursor and nothing seems to happen.  I moved the  host cursor oover the clover boot manager and clicked.  The cursor disappeared but nothing visible seemed to be going on.
3.   VirtualBoxVM is consuming 100% of the CPU
**Expected behavior**

**Additional context**
 - log file (see ```~/Library/Logs/runMojaveVirtualbox.log
[runMojaveVirtualbox.log](https://github.com/AlexanderWillner/runMacOSinVirtualBox/files/2590833/runMojaveVirtualbox.log)
``` that is accessible via ```Console.app```).
 - screen shot

**Comment by AlexanderWillner** [comment]
I removed clover from the setup. So might be fixed now.

**Comment by judoal** [comment]
Thanks for the update.  I wanted to do a test installation of macOS to test a few apps (esp time machine to my NAS drive). I gave up and installed ir on an external USB drive.

Allen Gordon, PhD, CISSP
