### ISSUE TITLE
sudo asking for password every time

### ISSUE THREAD

**Issue by RobbieClarken** [AlexanderWillner/runMacOSinVirtualBox#41]
Hi,

I used `make all` to create a Mojave 10.14.1 VM and it worked flawlessly. I have just encountered one strange issue inside the guest OS: I am required to enter my password for `sudo` every time. Normally `sudo` will only ask once and then not prompt again for 5 minutes.

This is on a fresh install where the only command I have run is `sudo sh /Volumes/NO\ NAME/moveCloverToEFI.sh`. I use a standard macOS user account (not linked to Apple ID).

I have tried setting `timestamp_timeout` in `/etc/sudoers` and creating a 2nd user account. The same thing happens. I thought it might be a time sync thing but my guest OS clock has the right time. Running `sudo visudo -c` reports:

```
/etc/sudoers: parsed OK
```

The permissions on `/etc/sudoers` and `/etc/sudoers.d/` are the same as my host Mojave where `sudo` works normally.

Has anyone else encountered this? Any idea how to debug it?

**Comment by AlexanderWillner** [comment]
Actually, haven't figured out the reason for this.
