### ISSUE TITLE
Update OS causes crash

### ISSUE THREAD

**Issue by malcsmith** [AlexanderWillner/runMacOSinVirtualBox#43]
**To Reproduce**
0. OS is just installed and account with iCloud linkage setup
1. Go to Settings -> Update OS
2. Click on Update OS (10.14.1)

3. OS update fails - core dump appears to be produced - "shutdownStall" file. Log is binary not text.

Update would complete by normal process.

Is this a bug or am I not choosing the right Clover image for the boot?

**Comment by AlexanderWillner** [comment]
Is this reproducible? Sometimes shutdown/restart doesn’t work.

**Comment by malcsmith** [comment]
Sadly no. it seems to occur randomly. I think it is related to speed of reading of the cdrom image file. (I had it on a network drive which seemed to cause an different type of clover boot).

I still can't reliably reproduce. And the system has now updated. (I think it is associated with OS updates the require special preboot to permit update of OS specific libraries/files).
