### ISSUE TITLE
Screen garbled after Clover start of MacOS install

### ISSUE THREAD

**Issue by mirogl** [AlexanderWillner/runMacOSinVirtualBox#44]
**To Reproduce**
1. Go to 'Boot from Clover'
2. Select 'Boot MacOS Install from Mojave'
3. Press 'Enter'
4. Now the screen ist garbled - see screenshot

**Expected behavior**
Mac OS Terminal should be readable and the Installer should start

**Additional context**
I'm using the new VirtualBox 6 - Version 6.0.0 r127566 (Qt5.6.3)
<img width="633" alt="image" src="https://user-images.githubusercontent.com/46027543/50291625-58404a00-046f-11e9-81df-2bc9cf28959e.png">

**Comment by AlexanderWillner** [comment]
Related to #33 - the screen resolutions have to match: VM, Clover, VBox (I think v6 introduced new ways to change the resolution).

**Comment by mirogl** [comment]
Hi, yes - I tried already to change the resolutions according to #33  - but it didn't help.

**Comment by AlexanderWillner** [comment]
I removed clover from the setup. So might be fixed now.
