### ISSUE TITLE
Missing apfs.efi driver

### ISSUE THREAD

**Issue by irwir** [AlexanderWillner/runMacOSinVirtualBox#46]
https://github.com/AlexanderWillner/runMacOSinVirtualBox/blob/4e8d3d796e31d8fb782a783a08af68895aa81a9a/runMojaveVirtualbox.sh#L198

Does the script check that base system was mounted?
`make clover` goes on with the build and created an ISO file. The ISO would load, but no APFS disks would be visible because of the missing driver.

It was sufficient to change the script line to
`readonly FILE_EFI="/usr/standalone/i386/apfs.efi"`
That also simplified the process: no unpacking for the driver, and no deleting FILE_EFI in clean-up.

**Comment by AlexanderWillner** [comment]
Thanks!

**Comment by irwir** [comment]
That part was not addressed in commit:
> no deleting FILE_EFI in clean-up.

https://github.com/AlexanderWillner/runMacOSinVirtualBox/blob/eefe0571b58235b503077379d0b01f6ae34c51ca/runMojaveVirtualbox.sh#L265

**Comment by AlexanderWillner** [comment]
Good point!
