### ISSUE TITLE
vdmutil attach fails in patchEFI

### ISSUE THREAD

**Issue by aroper23** [AlexanderWillner/runMacOSinVirtualBox#49]
Your script runs fine until attempting to attach the vdi image in the patchEFI function, at which point it fails for me with a VDM API Error.

I ran vdmutil using the -verbose switch like so to get more details:
/usr/local/bin/vdmutil attach -verbose "/Users/aroper/VirtualBox VMs/Mojave 4GB RAM.vdi"

...and see this output:
Looking for VDM Contoller...
No service found.
Error 0x00000001 : VDM API Error.

I've googled for this vdmutil error and haven't found anything relevant. Any suggestions would be appreciated.

In case it matters, the version of Paragon VMDK Mounter that's installed is 2.4.

[runMojaveVirtualbox.log](https://github.com/AlexanderWillner/runMacOSinVirtualBox/files/2776823/runMojaveVirtualbox.log)

**Comment by AlexanderWillner** [comment]
Thanks for the feedback. Is the ```vdmutil``` the one from [Paragon](https://www.paragon-software.com/home/vd-mounter-mac-free/)?

**Comment by aroper23** [comment]
Yes, I installed by doing:
brew cask install paragon-vmdk-mounter

**Comment by AlexanderWillner** [comment]
Maybe  the Kernel Extension has not been acknowledged at the bottom of "macOS Preferences > Security & Privacy > General"?

**Comment by aroper23** [comment]
I had acknowledged the kernel extension, but apparently the MacBook must be restarted before the launchctl service will start. The patchEFI function worked after reinstalling paragon-vmdk-mounter (just to be safe) and restarting, and I'm in the macOS install now. Thanks for pointing me in the right direction.
