### ISSUE TITLE
Error while running make all

### ISSUE THREAD

**Issue by mnuthan1** [AlexanderWillner/runMacOSinVirtualBox#53]
**To Reproduce**
1. Go to 'Downloaded folder'
2. run  'make all'

**Additional context**
 - log file (see ```~/Library/Logs/runMojaveVirtualbox.log``` that is accessible via ```Console.app```).
 
```
Creating VM 'macOS-Mojave' (around 2 seconds)....
Adding APFS drivers to EFI in '/Users/nmallavaram/VirtualBox VMs/macOS-Mojave.vdi' (around 5 seconds)....
ERROR: Couldn't mount EFI disk: Error 0x00000001 : VDM API Error.
DEBUG: line 255 - command 'exit 92' exited with status: 92.
DEBUG: In ::patchEFI::main::main called at line 398.
DEBUG: From function ::patchEFI::main::main (line 398).
```

I am running this from Mac Pro

**Comment by AlexanderWillner** [comment]
You might have not acknowledged the installation of the KEXT in the macOS security preferences

**Comment by AlexanderWillner** [comment]
See #49

**Comment by AlexanderWillner** [comment]
Removed the dependency to vdmutil.
