### ISSUE TITLE
Only "EFI" (1MB) installation disk available when installing Mojave

### ISSUE THREAD

**Issue by jlc** [AlexanderWillner/runMacOSinVirtualBox#54]
Hi!

To reproduce, I've just clone the repository and "make all".
macOS Mojave image is in the Application folder, and VMWare + Ext have been installed (I've tried with both 5.2.26 and 6.0.4.

After having created the image, booting macos installer for the first time, clicking on the "install macos" menu, accept the license, macOS detect only one disk named "EFI" of size 1MB (with 414kB available), and nothing else, so nowhere to install macos... :(

It's an awesome job!!! Thank you so much!

**Comment by AlexanderWillner** [comment]
Now an additional step is needed in the installer to initialize the disk first. So in the disk utility within the installer you've create a partition first. This step was automated before, but I'm now trying to remove the dependency for the tool that I used before.

**Comment by jlc** [comment]
Thank you! :)

But...

With version 1.2 as well as the current code, after about 75% of installation macOS installer never finish and keep rebooting the guest os, impossible to finish the installation.
(I've tried with virtual box 5.2.26 and 6.0.4, formating the disk in APFS or HDFS+).

Should I open a new ticket? Do you need more info?

**Comment by AlexanderWillner** [comment]
You've to eject the installer after it reboots. That's why there is the line ```Press enter to stop VM 'macOS-Mojave' (e.g. after installer restarted)....``` within the ```make all``` target.

**Comment by AlexanderWillner** [comment]
Also see Item 3 at https://github.com/AlexanderWillner/runMacOSinVirtualBox#faq

**Comment by jlc** [comment]
Work perfect!!!
