### ISSUE TITLE
VM hung at reboot

### ISSUE THREAD

**Issue by rogetnoprl** [AlexanderWillner/runMacOSinVirtualBox#57]
Installed MacOS and everything is fine except cannot reboot. if using clover 4833 vbox reboot/shutdown will throw an error, if updated to latest clover will hung at Mach reboot(shutdown is fine)
I searched via google, add drop table to config.plist but no use. would you look into it? Thanks a lot
<img width="521" alt="screen shot 2019-02-19 at 2 56 12 pm" src="https://user-images.githubusercontent.com/47734537/52996505-c9dd4a00-3458-11e9-994f-bcd256593f57.png">
<img width="935" alt="screen shot 2019-02-19 at 3 09 35 pm" src="https://user-images.githubusercontent.com/47734537/52996510-cd70d100-3458-11e9-8e26-3a17f5909fba.png">

[Log.zip](https://github.com/AlexanderWillner/runMacOSinVirtualBox/files/2878748/Log.zip)

my physical machine is MacBook Pro (13-inch, 2017, Two Thunderbolt 3 ports) 2.5 GHz Intel Core i7 16G RAM, os is 10.13.3 vbox ver is 5.2.26

**Comment by AlexanderWillner** [comment]
There were some issues with Clover (for example this one, that was not reproducible on my machine). Therefore, the current version of the script does not use Clover anymore.

**Comment by rogetnoprl** [comment]
Oh I am sorry I didn't notice FAQ. Thank you! How do you make vbox to support APFS in current version? I checked code and find there are still clover there. Seems you copied "$FILE_EFI" /Volumes/EFI/EFI/drivers/ , it that all Vbox needed to support APFS? Thanks a lot

**Comment by AlexanderWillner** [comment]
Haven't removed the clover code, yet. Current approach is to create a simple EFI System Partition (ESP), load the APFS driver in the ```startup.nsh``` and then boot from the APFS system partition.

**Comment by rogetnoprl** [comment]
I see the code. Will try it later, thank you again! Really appreciate your work, have a nice day!
