### ISSUE TITLE
Fails With Error

### ISSUE THREAD

**Issue by TexanScot** [AlexanderWillner/runMacOSinVirtualBox#6]
App doesn't work for me.  Output as shown below:

Running checks (around 1 second)....
Creating image '/tmp/macOS-Mojave.dmg' (around 20 seconds, version 14.0.11, will need sudo)...already exists.
Creating iso '/tmp/macOS-Mojave.iso.cdr' (around 25 seconds)....
ERROR: line 298 - command '[ $# -ne 0 ]' exited with status: 1.
ERROR: In :: called at line 0.
DEBUG: From function :: (line 0).

Any ideas?

**Comment by AlexanderWillner** [comment]
The interesting part is ```Error erasing disk error number (22, 0)```. Also ```hdiutil: convert failed - Resource temporarily unavailable```. Need some time to investigate on this. Have you tried after rebooting the machine?

**Comment by TexanScot** [comment]
So after a reboot of the machine I was able to progress further with installation. At present I have the grey screen that say's "MacOS Mojave Beta - Select the Disk Where You Want to Install MacOS."

However the install process seems to hang at this point (or is taking a very long time). Presently the screen has been at this point for at least 5 mins with no sign of progress. I'm installing on a Late 2013, 13" MBP. Is there a way to tell whether the install process is hung?

Thanks for your assistance with this by the way.

**Comment by TexanScot** [comment]
Actually it appears that the "Install" arrow is greyed out and is not active. I can select "back" from the screen which takes me back to the "Agree to License" selection however when I select "Agree" I end up back at the install screen with the greyed out button.

A problem with the configuration of the virtual machine?

**Comment by AlexanderWillner** [comment]
Have you formatted the drive? See Step 2 at https://github.com/AlexanderWillner/runMacOSinVirtualBox/blob/master/README.md#step-by-step-guide

**Comment by TexanScot** [comment]
Yeah, just realized that I had missed this step.  Can't seem to get back to the screen that offered disk utilities though - seems like I may need to go through the entire configuration process once more? 

I'll give it a go a little later and let you know how I fare.

Thanks.

**Comment by AlexanderWillner** [comment]
Actually, just clicking on ‚back’ or probably rather ‚quit‘ will be enough. No need to restart or do the whole process again.
