### ISSUE TITLE
Can't enter recovery mode

### ISSUE THREAD

**Issue by gabrielsouto** [AlexanderWillner/runMacOSinVirtualBox#60]
i've kept Cmd+R pressioned but Mac OS Mojave started normally

**Comment by digitalknk** [comment]
@gabrielsouto I believe that is a native mac device feature when it is virtualized or on non-mac hardware, it won't work.

**Comment by gabrielsouto** [comment]
But i´m using virtual box on a mid 2012 macbook pro

**Comment by gabrielsouto** [comment]
so, is there anyway to disable SIP?

**Comment by AlexanderWillner** [comment]
Actually, there is a recovery partition. However, it's not that simple to boot from it. What I tested:
1. Start VM as usual and press ```CMD+C``` then you see ```Trying to find a bootable device...```
2. ```fs4:``` > ```cd TAB``` > ```./boot.efi``` (note that using ```fs4``` was just a guess

![Screenshot 2019-04-06 at 19 52 12](https://user-images.githubusercontent.com/307605/55673239-84100000-58a5-11e9-8f35-19826af5c704.png)

**Comment by 0x5e** [comment]
Is there any way to go into single user mode? I download a vagrant image and seems that the author removed recovery hd. I heard that single user mode can disable SIP too.
