### ISSUE TITLE
VBoxManage: error: VDI: cannot create image 

### ISSUE THREAD

**Issue by ds1w** [AlexanderWillner/runMacOSinVirtualBox#62]
**To Reproduce**
i run sudo make all.  it errors out when it starts to create the VM.   I was able to run this once about a month ago.  i think it was the day you 

**Expected behavior**
You know what it's supposed to do.  :-)

**Additional context**
Attaching the log.  thanks!
[runMojaveVirtualbox.log](https://github.com/AlexanderWillner/runMacOSinVirtualBox/files/2985942/runMojaveVirtualbox.log)

**Comment by digitalknk** [comment]
Have you tried running a `clean` on it? It seems like it errors out because you have previously existing files. Also, I don't think you need to run `sudo` before, just let the script request it.

Hope that helps.

**Comment by ds1w** [comment]
Sorry. What’s a ‘clean’?
Thanks

**Comment by AlexanderWillner** [comment]
- Try ```sudo make clean``` then run again ```sudo make all```.
- If this doesn't work, try  ```sudo make clean stash``` then run again ```sudo make all```.
- If this doesn't work, try (warning: this deletes your virtual macOS disk image) ```sudo make clean stash stashvm``` then run again ```sudo make all```
