### ISSUE TITLE
Can not update to 10.14.4

### ISSUE THREAD

**Issue by DavidARivkin** [AlexanderWillner/runMacOSinVirtualBox#65]
**To Reproduce**
1. Go to https://support.apple.com/kb/DL1994?viewlocale=en_US&locale=en_US
2. Click on download
3. Open the DMG and run the package.
4. See error when you get to Destination Select section.

**Expected behavior**
APFS is not used in this so updates, (needed for us to install XCode etc0 are not possible.

**Comment by AlexanderWillner** [comment]
![Screenshot 2019-04-06 at 18 36 25](https://user-images.githubusercontent.com/307605/55672406-15c64000-589b-11e9-8f3d-96478ad5e8c6.png)

![Screenshot 2019-04-06 at 18 38 57](https://user-images.githubusercontent.com/307605/55672434-65a50700-589b-11e9-9ff6-99c2cc23fb93.png)

**Comment by AlexanderWillner** [comment]
seems to work
