### ISSUE TITLE
macOS-Mojave.efi.vdi drive visible and accessible in the VM

### ISSUE THREAD

**Issue by HigH-HawK** [AlexanderWillner/runMacOSinVirtualBox#67]
I don't think this is a bug of some kind but I noticed that when I start the VM, the drive with the EFI drivers `macOS-Mojave.efi.vdi` is being loaded as normal hard drive and also accessible from within the VM.

Did I maybe do something wrong during the setup process? How can I make sure that this drive is there but not shown in the VM / macOS.

Thanks in advance

**Comment by AlexanderWillner** [comment]
You can hide it using https://apple.stackexchange.com/questions/145683
