### ISSUE TITLE
Problem executing the script

### ISSUE THREAD

**Issue by cotfas** [AlexanderWillner/runMacOSinVirtualBox#73]
cotfas:runMacOSinVirtualBox work$ make all
Logfile: /Users/work/Library/Logs/runMacOSVirtualbox.log
Running checks (around 1 second)....
ERROR: No macOS installer found. Opening the web page for you (press enter in the terminal when done)...
DEBUG: You can also create an installer using the script 'installinstallmacos.py' (use Google)...

DEBUG: line 104 - command 'exit 6' exited with status: 6.
DEBUG: In ::runChecks::main::main called at line 373.
DEBUG: From function ::runChecks::main::main (line 373).
ERROR: Look at /Users/work/Library/Logs/runMacOSVirtualbox.log for details (or use Console.app). Press enter in the terminal when done...

make: *** [all] Error 6
cotfas:runMacOSinVirtualBox work$

**Comment by AlexanderWillner** [comment]
No macOS installer found.

**Comment by cotfas** [comment]
Still can not run it.


cotfas:runMacOSinVirtualBox work$ 
cotfas:runMacOSinVirtualBox work$ make all
Logfile: /Users/work/Library/Logs/runMacOSVirtualbox.log
Running checks (around 1 second)....
Creating image '/Users/work/VirtualBox VMs/macOS-VM.dmg' (around 20 seconds, version 14.3.2, will need sudo)...already exists.
Creating iso '/Users/work/VirtualBox VMs/macOS-VM.iso.cdr' (around 25 seconds)...already exists.
Creating VM HDD '/Users/work/VirtualBox VMs/macOS-VM.vdi' (around 1 minute)....
ERROR: Couldn't create /Users/work/VirtualBox VMs/macOS-VM.sparseimage
DEBUG: line 256 - command 'exit 95' exited with status: 95.
DEBUG: In ::createVM::main::main called at line 373.
DEBUG: From function ::createVM::main::main (line 373).
ERROR: Look at /Users/work/Library/Logs/runMacOSVirtualbox.log for details (or use Console.app). Press enter in the terminal when done...

make: *** [all] Error 95
cotfas:runMacOSinVirtualBox work$ 


Mac OS X Mojave

VirtualBox 6 with extended libraries

**Comment by cotfas** [comment]
It worked

**Comment by o6uoq** [comment]
@cotfas what did you do to get it working ?

**Comment by cotfas** [comment]
> @cotfas what did you do to get it working ?

This was the problem>>>

"Execute make all to setup and run everything. After the installer reboots, press enter in the terminal to finish the installation."
