### ISSUE TITLE
https://github.com/siemens/runMacOSinVirtualBox step 4 fails

### ISSUE THREAD

**Issue by virtualbox** [AlexanderWillner/runMacOSinVirtualBox#75]
**To Reproduce**
1. Go to https://github.com/siemens/runMacOSinVirtualBox
2. perform steps up to installing the OS at step 4. 
3. Over 10000 errors in Log before accept licence agreement. Continue anyway and after a few minutes of activity, install fails and system unexpectedly reboots
4. Repeat. No way to progress.
<img width="1372" alt="Screenshot 2019-07-01 at 21 49 34" src="https://user-images.githubusercontent.com/52428151/60465913-2263f580-9c4a-11e9-88b1-dd8331e04616.png">

**Expected behavior**
I expected the install to complete. Instead Mojave has 6GB of partial install stuff and no bootable OS.

**Additional context**
Log files trapped inside a partial install so not easily accessible
<img width="1372" alt="Screenshot 2019-07-01 at 21 49 34" src="https://user-images.githubusercontent.com/52428151/60466004-63f4a080-9c4a-11e9-9c52-55f7ad94b3c8.png">
<img width="1372" alt="Screenshot 2019-07-01 at 21 51 15" src="https://user-images.githubusercontent.com/52428151/60466005-63f4a080-9c4a-11e9-9092-53d3d2379665.png">
<img width="1372" alt="Screenshot 2019-07-01 at 21 53 07" src="https://user-images.githubusercontent.com/52428151/60466136-bafa7580-9c4a-11e9-95b0-bb32ea9469de.png">

**Comment by AlexanderWillner** [comment]
Thanks for the feedback. This is a tough one. Hard to say, my best guess is that the generate VDI file is somehow broken - not sure how and why though as ```ìt works for me```. My approach would be to debug the method ```createVM``` to see if there is something of interest. Maybe the VDI file is created on a network drive?

**Comment by AlexanderWillner** [comment]
Closing stalled issues.
