### ISSUE TITLE
installer not found

### ISSUE THREAD

**Issue by 708145h** [AlexanderWillner/runMacOSinVirtualBox#78]
**To Reproduce**
Steps to reproduce the behaviour:
script fails to recognise installer in applications folder for Mojave, precedes to open browser page for beta program to download a new installer

**Additional context**
Running checks (around 1 second)....
ERROR: No macOS installer found. Opening the web page for you (press enter in the terminal when done)...
DEBUG: You can also create an installer using the script 'installinstallmacos.py' (use Google)...

**Comment by AlexanderWillner** [comment]
The script looks for ```/Applications/Install macOS *``` - this is the default name. How is your installer named?

**Comment by o6uoq** [comment]
> The script looks for `/Applications/Install macOS *` - this is the default name. How is your installer named?

☝️ this should be added to the documentation/README.
