### ISSUE TITLE
Please fix in readme.md file (make all->sudo make all)

### ISSUE THREAD

**Issue by XMR888** [AlexanderWillner/runMacOSinVirtualBox#79]
Hello, Alexander!

Thanks for your great job.

Please fix in readme.md file

`make all`

to 

`sudo make all`

Without "sudo" install break in step 2.

**Comment by Patronics** [comment]
It worked fine for me without sudo, it automatically prompted for root's password when needed

**Comment by haakonstorm** [comment]
@XMR888 You need to read up on permissions. You don't generally want to grant `make` super-user permissions when you're doing a local install. If you disagree please state so and provide more details, if not, you are encourage to close the issue you opened.

That said, @AlexanderWillner need to check up on the makefile. The way it is set up now, on first run, many users will encounter what @XMR888 did, namely that on first run you won't get any prompt for escalating privileges, and build will fail. However, on second run, you will get "Password: ...".
Don't have time to find the particular problem right now but it's easily reproducibe by creating new vanilla user and try a first time `make all` in that context.

**Comment by AlexanderWillner** [comment]
Thanks for the feedback. However, couldn't reproduce this issue - even not with a complete new user. Maybe fixed by now.
