### ISSUE TITLE
Where's macOS-Mojave.iso.cdr for downloading?

### ISSUE THREAD

**Issue by just4id** [AlexanderWillner/runMacOSinVirtualBox#8]
Good job, but where's macOS-Mojave.iso.cdr for downloading?

Thank you.

**Comment by AlexanderWillner** [comment]
You‘ve to download the installer app via https://beta.apple.com/sp/betaprogram/redemption#macos - the iso file will be generated based on this.

**Comment by jeff-h** [comment]
For anyone else wondering where to get the disk image, this may be helpful: https://www.macworld.com/article/3284378/os-x/how-to-create-a-bootable-macos-mojave-installer-drive.html

Short story, get it through the app store, after which it will launch automatically. "But don’t continue with the installation. Instead, press Command-Q on your keyboard to quit the installer."

**Comment by thelamehacker** [comment]
Here is a bash script that I wrote for creating the ISO after downloading. This is my first bash script so I would also appreciate any feedback and improvements. Thanks.

https://github.com/thelamehacker/macOS-toolkit/blob/master/toolkit/macOS_Mojave_ISOMaker.sh
