### ISSUE TITLE
Mojave Issues

### ISSUE THREAD

**Issue by Lucifer-5** [AlexanderWillner/runMacOSinVirtualBox#81]
**To Reproduce**

**Expected behavior**
After doing every step told here [https://www.intoguide.com/install-macos-mojave-virtualbox-windows/] i am booting all fine, but after the apple logo my whole screen turns gray. does this os requires u to download it from mac os high seirra? then update it?

**Comment by AlexanderWillner** [comment]
Thanks for the issue. However, the guide has nothing to do with this project. Can't really know what's happening when using the provided ISO that is mentioned on the website.
