### ISSUE TITLE
Feature Request: Set Serial Number

### ISSUE THREAD

**Issue by danmandle** [AlexanderWillner/runMacOSinVirtualBox#86]
I've used [this tool](https://github.com/chilcote/vfuse) which is very similar to your's, but for VMWare Fusion. The major feature I used with it is to set the serial number which is required for my use case. Have you considered adding that feature to this package?

**Comment by danmandle** [comment]
Doing some research, looks like it wouldn't be very hard to set: https://superuser.com/a/378302

I'll look into integrating that and doing a pull request.

**Comment by AlexanderWillner** [comment]
That would be great.

**Comment by AlexanderWillner** [comment]
Fixed in c5ac7d2bd94589a0d28f2e36ee2c1234b5dd152a
