### ISSUE TITLE
Remove dmg and sparse image files, or note such

### ISSUE THREAD

**Issue by kkieffer** [AlexanderWillner/runMacOSinVirtualBox#88]
Great project, worked like a charm.  Would be worth noting in the help that the dmg files and sparseimage files created by the script can be deleted after the VM is up and running, to save disk space.

Or, delete them automatically from the script.

**Comment by vladimirf7** [comment]
I had the same question.
@kkieffer run `make clean` after your VM installation is completed. This will remove those files.

**Comment by AlexanderWillner** [comment]
Thanks for the feedback. Yes, `make clean` should solve this and is documented.
