### ISSUE TITLE
This copy of the Install macOS Mojave application is damaged and can't be used to install macOS.

### ISSUE THREAD

**Issue by sourcedelica** [AlexanderWillner/runMacOSinVirtualBox#89]
I'm trying to install MacOS Mojave.

**To Reproduce**
1. Edit `runMacOSVirtualbox.sh` and remove `--applicationPath` like:
```
-    sudo "$INST_BIN" --nointeraction --volume "$DST_VOL" --applicationpath "$INST_VER" ||
+    sudo "$INST_BIN" --nointeraction --volume "$DST_VOL" "$INST_VER" ||
```
2. Create installer using default settings:
```
$ make all
Logfile: /Users/eric/Library/Logs/runMacOSVirtualbox.log
Running checks (around 1 second)....
Creating image '/Users/eric/VirtualBox VMs/macOS-VM.dmg' (around 20 seconds, version 14.2.2, will need sudo)....
Password:
Creating iso '/Users/eric/VirtualBox VMs/macOS-VM.iso.cdr' (around 25 seconds)....
Creating VM HDD '/Users/eric/VirtualBox VMs/macOS-VM.vdi' (around 1 minute)....
Adding APFS drivers to EFI in '/Users/eric/VirtualBox VMs/macOS-VM.efi.vdi' (around 5 seconds)....
Creating VM 'macOS-VM' (around 2 seconds)....
Adding installer DVD for VM 'macOS-VM'....
Adding APFS drivers to EFI in '/Users/eric/VirtualBox VMs/macOS-VM.efi.vdi' (around 5 seconds)....
Starting VM 'macOS-VM' (3 minutes in the VM)....
Press enter to stop the VM and to eject the installer medium (to avoid an installation loop)....
```
The installer starts and I click on Install macOS.

Afterwards, an error is displayed:
This copy of the Install macOS Mojave application is damaged and can't be used to install macOS.

**Additional context**
![image](https://user-images.githubusercontent.com/4219652/69014608-e790fe80-0959-11ea-8dc5-60ef86a38927.png)

**Comment by sourcedelica** [comment]
I got this working with Catalina so I'm going to close this out.  I'm assuming something was wrong with my Mojave.

**Comment by o6uoq** [comment]
@sourcedelica what version of Catalina?

**Comment by sourcedelica** [comment]
It was either 10.15.1 or 10.15.2.  It is 10.15.2 currently but I may have updated the OS via Software Update.
