### ISSUE TITLE
Upgrade to 10.15.2

### ISSUE THREAD

**Issue by HoudayerPierre** [AlexanderWillner/runMacOSinVirtualBox#91]
**To Reproduce**
1. Download upgrade and Reboot
2. Boot on Catalina (not booting on macOS install data)
3. macOS version is still 10.15.1

**Expected behavior**
The upgrade from 10.15 to 10.15.1 works,
but the upgrade from 10.15.1 to 10.15.2 is not booting on the macOS install data.

**Additional context**
 - The disk with startup script is in the VM (sata 1) and the main disk is sata 2
 - no boot by hand in the shell
 - Clover wont boot either

**Comment by vitaliy-solarwinds** [comment]
Also macOS 10.15.2 can't be installed

**Comment by Kerndog73** [comment]
I get stuck on this screen when I try to install 10.15.2.

![screenshot](https://user-images.githubusercontent.com/10371177/70693781-0e024980-1d0e-11ea-9e81-34d613e555f2.png)

**Comment by dumol** [comment]
So I was lucky not to have the disk space to install 10.15.2? :-]

Actually came here to file an issue for the default size of the VM disk, which prevents installing large updates, such as this one…

**Comment by HarDToBelieve** [comment]
> I get stuck on this screen when I try to install 10.15.2.
> 
> ![screenshot](https://user-images.githubusercontent.com/10371177/70693781-0e024980-1d0e-11ea-9e81-34d613e555f2.png)
> 
> It's making me even more anxious about installing Catalina on my real machine!

I met the same problem, is there anyone who have fixed this?

**Comment by HoudayerPierre** [comment]
> > I get stuck on this screen when I try to install 10.15.2.
> > ![screenshot](https://user-images.githubusercontent.com/10371177/70693781-0e024980-1d0e-11ea-9e81-34d613e555f2.png)
> > It's making me even more anxious about installing Catalina on my real machine!
> 
> I met the same problem, is there anyone who have fixed this?

I had this problem with **Clover** you can try this :
From [https://www.nicksherlock.com/2019/10/installing-macos-catalina-10-15-on-proxmox-6/]
-> "you must untick the “AudioDxe” driver during installation, because this causes Clover to hang."
I remove it and it boot.

**Comment by HoudayerPierre** [comment]
But on VirtualBox I have something else : 
<img width="657" alt="Capture d’écran 2019-12-12 à 11 00 36" src="https://user-images.githubusercontent.com/12223438/70907054-21f8c480-2008-11ea-94d3-68723ed381ae.png">
or
<img width="853" alt="Capture d’écran 2019-12-16 à 13 24 29" src="https://user-images.githubusercontent.com/12223438/70907064-27eea580-2008-11ea-9cb1-dad95a227423.png">
Nothing happen after "+++++++++++++++++++++++" ...

**Comment by HoudayerPierre** [comment]
Something to try here :
https://github.com/myspaghetti/macos-guest-virtualbox/issues/134#issuecomment-578764413

**Comment by HoudayerPierre** [comment]
It will be fixed for the next maintenance release :
https://www.virtualbox.org/ticket/19188#comment:8

**Comment by kfinley** [comment]
@AlexanderWillner, This may be helpful if Oracle doesn't get the EFI boot issue fixed soon. Nice project btw. :)

https://github.com/kfinley/macos-on-virtualbox

**Comment by HoudayerPierre** [comment]
VirtualBox released VirtualBox 6.1.4 (released February 19 2020)

This is a maintenance release. The following items were fixed and/or added:

Virtualization core: Fixed macOS Catalina guests failing to boot after upgrading to 10.15.2 onwards (bug #19188)

=> it's working !
