### ISSUE TITLE
Failing to install 10.15.2 guest VM on 10.15.2 host

### ISSUE THREAD

**Issue by jaanus** [AlexanderWillner/runMacOSinVirtualBox#95]
**To Reproduce**

1. Have Catalina 10.15.2 installed, the official installer downloaded from System Update.
2. Clone this script.
3. Run `make all`.
4. VM is created and installation boots, but VM has blank screen, just stays hanging in blank state.

**Expected behavior**

VM should install without errors.

**Additional context**

[runMacOSVirtualbox.log](https://github.com/AlexanderWillner/runMacOSinVirtualBox/files/4014066/runMacOSVirtualbox.log)

<img width="1178" alt="Screenshot 2020-01-01 at 14 54 50" src="https://user-images.githubusercontent.com/184253/71641574-f7189c80-2ca6-11ea-89c7-542a020efe42.png">

<img width="908" alt="Screenshot 2020-01-01 at 14 54 42" src="https://user-images.githubusercontent.com/184253/71641576-fb44ba00-2ca6-11ea-9561-41cb85c0c50d.png">

**Comment by jaanus** [comment]
Probably a duplicate of #93, but wanted to upload a fresh set of log and steps.

**Comment by myspaghetti** [comment]
[pbe](https://forums.virtualbox.org/viewtopic.php?f=22&t=96078&sid=bef68cf17d9eaf8317314214dbc954db&start=15#p468626) found a workaround, replace the Catalina 10.15.2 `boot.efi` with one from an earlier version of macOS. Both 10.15.1 and 10.14.6 work.

**Comment by kfinley** [comment]
This may help.. Automated solution of workaround  https://github.com/kfinley/macos-on-virtualbox

**Comment by AlexanderWillner** [comment]
Thanks, nice toolkit. Seems Oracle will fix it in the next update: https://www.virtualbox.org/ticket/19188

**Comment by jaanus** [comment]
Cool. I’ll re-test once the Virtualbox fix is released.

**Comment by nieder** [comment]
Vbox 6.1.4 has been released and 10.5.1 -> 10.5.3 update worked for me now.

**Comment by jaanus** [comment]
Yep, works now.
