### ISSUE TITLE
[Question] Is there a way to use the script just to create ISO ?

### ISSUE THREAD

**Issue by leonardo-sj** [AlexanderWillner/runMacOSinVirtualBox#96]
Due to known [Virtual Box bug  in Mac OSX Catalina 10.15.2](https://www.virtualbox.org/ticket/19188), I intend to use VMWare.
Is it possible to use this script just to generate the ISO and use it with VMWare ?

**Comment by AlexanderWillner** [comment]
You mean `make installer`?

**Comment by leonardo-sj** [comment]
Thanks. It's generating macOS-VM.iso.cdr (10.74 GB), but the boot in VMWare isn't working with this file.

**Comment by AlexanderWillner** [comment]
Thanks for the feedback. Actually not using VMWare. Closing stalled issues.

**Comment by Ashtonian** [comment]
would like this for esxi
